### ISSUE TITLE
文書ごとにタグが変わらない

### ISSUE THREAD

**Issue by KEINOS** [hidao80/TsumiQiita#28]
## 現象

登録したタグが、他の Markdown ファイルに切り替えても同じタグになる。

## 再現方法

1. 複数 MD ファイルを登録する
2. タグを登録する
3. 文書を切り替える
4. タグは変わらない

## 環境
- インストール方法
    - `npm run build` でアプリをビルド後、アプリケーションフォルダにアプリを移動
- `git describe --tags`: 1.3.0
- `npm -v`: 6.0.0
- `node -v`: v9.11.1
- `npm config get registry`:  https://registry.npmjs.org/
- OS: macOS HighSierra
    - MacBook Pro (Retina, 13-inch, Early 2015)
    - `sw_vers`:
        - ProductName:	Mac OS X
        - ProductVersion:	10.13.4
        - BuildVersion:	17E199

**Comment by hidao80** [comment]
@KEINOS 🤔 
Markdown ファイルには記事のみを載せたいので、メタ情報の取り扱いは悩んでおります。\
同様の理由で、記事のタイトルもファイル名から撮る仕様となっています。

現在の仕様では Markdown ファイルにメタ情報を持たせておらず、また Markdown ファイルに対となるメタ情報データベースも持ち合わせていません。\
ですので、タグの切替えををしようにも**切替えると揮発してしまうので切替えてない**のが現状です。

Markdown フォーマットのままファイルにメタ情報を持たせる方法を考えますので、次のバージョンで解決し次第本 isssue を close します。

ご意見ありがとうございます。 🙇
