### ISSUE TITLE
コピペができません

### ISSUE THREAD

**Issue by KEINOS** [hidao80/TsumiQiita#37]
### 現象

TsumiQiita の本文およびトークン入力欄でコピー＆ペーストが出来ません。

### 詳細

- TsumiQiita : v1.40 -> v1.5.0 （リリースページからダウンロードしたバイナリ）
- macOS HighSierra: OSX 10.13.5
- `node -v` : v8.11.3
- `npm -v` : v5.6.0

こんにちは。私は TsumiQiita のユーザです。独身です。最近 TsumiQiita で Markdown ファイルを楽しく積んでいますが、コピペで詰んでおり、コピペピピックです。

と言いますのも、新規作成や既存 `.md` ファイルの編集・保存などは問題ないのですが、コピーおよびペーストのショートカットが働かず、右クリックも出てきません。

Wine アプリなどで良くある FEP/IME の問題（変換処理が入るためショートカットコマンドが渡せていない問題）かと思い、以下で「直接入力」を試してみましたが NG でした。

- 「日本語環境設定」（キーボードの入力ソース）を開き「U.S.」の入力ソースを追加後、英語モードで直接入力

このことから、おそらく IME がショートカット・コマンドを渡せていないのではなく、Electron 側が拾えていないのではないか、と感じました。

また、TsumiQiita のバージョンが v1.4.0 だったので、新しいバージョン（v1.5.0）のインストール（ダウンロード＆上書き）も行いましたが変化はありませんでした。

他に何か試せることはありますでしょうか。

一連の文書入力後にコピペで体裁を整えたりすることが多いため、もし仕様でしたら以後のバージョンでのご対応を検討いただけると、これ幸いです。

**Comment by hidao80** [comment]
ご報告ありがとうございます。

おっしゃる通り、現在macOS向けにビルドされた electron アプリでは、デフォルトでショートカットキーによるコピペが効かないようです(未検証、Web 上の情報による)。

時期バージョンにて対応し、早急にリリースする事を約束いたします。

少々お待ちください。🙇‍♂️

**Comment by KEINOS** [comment]
こちらこそ、既知既出である旨、下調べもせずに issue をあげてしまい申し訳ありません。

ざっと調べただけでも以下のような情報が出てきましたので、自分でも試してみたいと思います。

- [MacでElectronするとクリップボードが効かなくなるときの対処](https://qiita.com/hachi8833/items/12a06c5ba895f95eaf67) @ Qiita
- [Mac OSX用にパッケージ化したアプリはCMD+C,CMD+Vによるコピー＆ペーストができない。](https://qiita.com/nyamogera/items/81832dccb57054fbd406) @ Qiita
- [Mac OS X Pasteboard Access Under tmux And screen](https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard#mac-os-x-pasteboard-access-under-tmux-and-screen) | tmux-MacOSX-pasteboard @ GitHub
- [Electron - Enable copy and paste](https://pracucci.com/atom-electron-enable-copy-and-paste.html) @ Marco Pracucci

**Comment by hidao80** [comment]
お待たせしました。

[mac0S でコピペができない不具合解決版](https://github.com/hidao80/TsumiQiita/releases/tag/1.5.1)をリリースしました。

上記リンクよりバージョン 1.5.1 をお試しください。

最新ソースからビルドしていただくこともできます。

**Comment by KEINOS** [comment]
動作確認できました！
macOS版だけメニューがあるのも贅沢な気がしますが、早速のご対応、ありがとうございます！
