### ISSUE TITLE
ボルドーは良いんですが （Bタグ記法の要望）

### ISSUE THREAD

**Issue by KEINOS** [hidao80/TsumiQiita#38]
## 要望

「`フランスの␣**ボルドー地方のワイン**␣をいう`」と、`**`の前後にスペースを入れなくてもボルドー（強調表示）するようにして欲しいです。（GitHub Flavored Markdown と言うのかしら？）

## 詳細

こんにちは。私は現在、神奈川におります四十路の独身エンジニアです。趣味はハラペーニョです。最近 TsumiQiita で積んでは崩しを繰り返して遊んでいます。

さて、Qiita や GitHub では「`フランスの**ボルドー地方のワイン**をいう`」と、「`**`」の前後にスペースなしの記法でボルドー（強調表示）になります。

TsumiQiita では、「`フランスの␣**ボルドー地方のワイン**␣をいう`」と、「`**`」の前後にスペースを入れないとボルドーになりません。（Kobito も同じ仕様です）

- 「フランスの**ボルドー地方のワイン**をいう」← Qiita & GitHub
- 「フランスの **ボルドー地方のワイン** をいう」← TsumiQiita & Kobito

上記のように強調の前後に空白が空くため、より強調されることになり、ある意味これはこれでスタイルの問題（解釈の仕方）とも思われます。

もし強調の前後の空白がデザイン・ポリシーであれば、それはそれで良いのですが、空白は CSS 側にさせるべきとも感じます。

というのは後付けで、レンダリング後のドキュメントをテキストとして使うためにコピペすると不要な空白も一緒に付いて来てしまうので、Qiita にアップ後スペースを削除する工程を入れているのですが、面倒に感じて来たので要望をあげました。

まことに勝手な個人的要望ですが、**お手すきで結構です**ので、仕様変更をご検討いただければと存じます。

### 環境

- TsumiQiita : v1.5.1 （リリースページからのダウンロード・バイナリなり）
- OS: macOS HighSierra (OSX v10.13.5)
- `node -v` : v8.11.3
- `npm -v` : v5.6.0

**Comment by KEINOS** [comment]
どうやら、**スペースを入れなくても強調されるケースもある**ようです。

と言うより、そもそも基本はスペースなしでも強調され、`「」` などの文字が`**`の後にあるとレンダリングに影響するようです。

以下の例では「強調表示を〜」の部分にはスペースはないのですが、ちゃんと強調表示されています。

２つめではスペースを入れると正常にレンダリングされますが、３つめのスペースのない例では、最初の「`**`」がエスケープされて、強調がズレてしまいます。

```
# スペースは「␣」に置き換え
1. ボルドー地方のワインを**ボルドーワイン**といい、強調表示を**ボルドー**という。
2. ボルドー地方のワインを␣**「ボルドーワイン」**␣といい、強調表示を**ボルドー**という。
3. ボルドー地方のワインを**「ボルドーワイン」**といい、強調表示を**ボルドー**という。
```

上記は以下のように表示されます。

<kbd><img width="661" alt="2018-06-20 10 29 50" src="https://user-images.githubusercontent.com/11840938/41632440-eb6311fe-7474-11e8-8a22-6da9557220c8.png"></kbd>


おそらく、これは Markdown のパーサーのライブラリ側の問題のようです。正規表現うんぬんの一筋縄では済みそうにない仕様かもしれませんね、、、

**Comment by hidao80** [comment]
@KEINOS 
kobito-oss 様のパッケージを解析したところ、Markdown レンダリングエンジンに “marked” というライブラリを採用されていました。

一方、拙作 TsumiQiita では Markdown レンダリングエンジン ( = パーサ ) に “markdown-it” を採用しています。kobito-oss 様と TsumiQiita のレンダリング揺れに関してはこれが原因だと考えられます。

さらに、「記号を伴う意図しない Markdown のレンダリング」は、GitHub のコメント欄でも発生し、**現行 Markdown レンダリングエンジンの不具合またはデファクトスタンダードである**と解釈しています。

そもそもモダンな Markdown レンダリングエンジンが「**単語ごとにスペースの入る言語圏で開発されたもの** 」という出自があり、日本語の文章のように記号と本文をスペースで分けずに記述したものをパースしきれていないのではないかという疑問もあります。

ともあれ、人のせいにするのもなんなので、回避方法を調査してみます。

ご提案ありがとうございます。

**Comment by hidao80** [comment]
@KEINOS 
暫定的な回避策を発見しましたのでご報告します。
1.のような文章があるとして、2. のように記述すると意図した表示をさせることができます。
Markdown のレンダリングの中間出力に HTML5 が使われれることを利用した Markdown hack です。

1. うまくいかない例
    `ボルドー地方のワインを**「ボルドーワイン」**といい、強調表示を**ボルドー**という。`
    ボルドー地方のワインを**「ボルドーワイン」**といい、強調表示を**ボルドー**という。
2. 回避例
    `ボルドー地方のワインを<wbr>**「ボルドーワイン」**<wbr>といい、強調表示を**ボルドー**という。`
    ボルドー地方のワインを<wbr>**「ボルドーワイン」**<wbr>といい、強調表示を**ボルドー**という。

ご参考まで。

**Comment by KEINOS** [comment]
> Markdown レンダリングエンジンが「単語ごとにスペースの入る言語圏で開発されたもの 」という出自があり

確かに、そこら辺の MeCab を必要としない言語圏との違いは十分にありそうですね！ 想像に難くない気がします。

嗚呼、私にもライブラリを吸ったり揉んだり出来る技術があれば良いのに、と思います。

> Markdown のレンダリングの中間出力に HTML5 が使われれることを利用した Markdown hack です。

なるほど！Mastodon で言う「ZWS 」(Zero Width Space) の遊びと同じ「見えないがそこにあるスペース」戦法ですね！

「ZWS」だとレンダリング後にも無幅のスペースが入ってしまい、それはそれで微妙に困るな、と思っていました。

ただ残念なことに、ご提案の文法で Qiita では正常に表示されることは確認したのですが、TsumiQiita （macOS版）のプレビューだと「`<wbr>`」のタグが表示されてしまいます。

1. 入力
    `ボルドー地方のワインを<wbr>**「ボルドーワイン」**<wbr>といい、強調表示を**ボルドー**という。`
2. Qiita 出力（レンダリング結果）
    <kbd><img width="611" alt="2018-06-21 11 16 17" src="https://user-images.githubusercontent.com/11840938/41694298-90fa2aa6-7544-11e8-935c-f2d1e410fd7c.png"></kbd>
3. TsumiQiita 出力（レンダリング結果）
    <kbd><img width="701" alt="2018-06-21 11 05 23" src="https://user-images.githubusercontent.com/11840938/41694271-78e51746-7544-11e8-8913-63eefbd1d901.png"></kbd>

### 考察と検証

ボルドーの処理は出来ているので、ご案内いただいた手法で**ちゃんと区切りとしては認識されている**ようです。

となると `<wbr>` タグが 使用可能な HTML タグとして許可されていないのでは、と思われます。

[レンダリングを呼び出している箇所](https://github.com/hidao80/TsumiQiita/blob/master/src/js/functions.js#L35-L49)の設定（定義？）なのかなと思うのですが、何をどう設定するのか、よくわかりませんでした。 (><) 

おそらく [`set` メソッド](https://markdown-it.github.io/markdown-it/#MarkdownIt.set) 付近の設定だと思うのですが、とりあえず [Markdown-it のオンライン検証 Demo](https://markdown-it.github.io/) を触って、色々イジってみました。

その結果、デフォルト設定値で同じ現象（`<wbr>`タグが表示されてしまう現象）が確認できたのですが、以下の設定項目のいずれかにチェックを入れると正常（期待する結果）に表示されました。

1. `html` をオン
2. `CommonMark Strict` をオン

#### 検証データ

```
#### wbr esc:
ボルドー地方のワインを<wbr>**「ボルドーワイン」**<wbr>といい、強調表示を**ボルドー**という。

#### none wbr:
ボルドー地方のワインを**「ボルドーワイン」**といい、強調表示を**ボルドー**という。
```

1. デフォルト出力
    <kbd><img width="532" alt="2018-06-21 11 47 25" src="https://user-images.githubusercontent.com/11840938/41695332-95447918-7549-11e8-89e4-be6960443ddd.png"></kbd>
2. 「`html` をオン」の出力
    <kbd><img width="530" alt="2018-06-21 11 47 50" src="https://user-images.githubusercontent.com/11840938/41695356-ab755888-7549-11e8-833c-90758deffb21.png"></kbd>
3. 「`CommonMark strict`をオン」の出力
    <kbd><img width="530" alt="2018-06-21 11 48 37" src="https://user-images.githubusercontent.com/11840938/41695397-cfc1f0c0-7549-11e8-806e-3c372a0de653.png"></kbd>


レンダリング結果（`source`）をみると、(2) の **"CommonMark Strict" の方が html エスケープもされており安全そうな印象を受けました**。

しかし、その場合は以下の設定をして `CommonMark` モードにする（`CommonMark`ルールを使う？）必要があるらしく、その場合 GitHub flavor / Qiita flavor が損なわれる気もします。

```
// commonmark mode
var md = require('markdown-it')('commonmark');
```

**Comment by hidao80** [comment]
@KEINOS 
検証ありがとうございます！ まさか、TsumiQiita がデフォルトで`<wbr>`に対応していないとは…くっ、k (ry

当方未検証ですが、`html=on`を検討しています。

**Comment by hidao80** [comment]
試しに 

```javascript:functions.js
const md = require('markdown-it')('commonmark'){
/// set config...
}.enable(['table', 'strikethrough'])
.use(require('markdown-it-checkbox'));
```

としてみたら、CommonMarkdown に表組みと打ち消し線とチェックボックスを輸入できました。

出力 HTML の検証はしていませんが、`<wbr>`は ZWSP として仕事をしてくれるのでよしとしたいところです。

**Comment by KEINOS** [comment]
早速のご対応ありがとうございます！

[TsumiQiita v.1.6.0](https://github.com/hidao80/TsumiQiita/releases/tag/1.6.0) のバイナリで `<wbr>` タグが働いた（表示されないようになった）のを確認しました。また、併せて表組みやチェックボックスの動作確認も取れました！

これでまた利用の幅が広がりました。ありがとうございます！

とりあえず暫定対処でも `<wbr>`  タグで目的は達成できたので、この issue はクローズにしたいと思います。
