### ISSUE TITLE
ページ遷移すると戻れません

### ISSUE THREAD

**Issue by KEINOS** [hidao80/TsumiQiita#42]
## TL;DR

プレビューのリンクを踏むとページ遷移してしまい、エディタ画面に戻れません。

## TS;DR

最新の Mac 版 TsumiQiita で記事を書いている最中のプレビューでのチェック中、自身が書いているにも関わらず興味をそそられリンクをクリックしてしまいました。

当然のように画面遷移するのですが、戻ろうにも戻れず、それは、まるで穴があったら手を突っ込み、何かを握ったのでビックリして抜こうにも握ったままなので、抜けずに慌てる猿のようでした。

結局、腕を切り落とすかのごとくアプリを終了させないといけませんでした。

ショートカットも効かないようなのですが、何か回避方法はありますでしょうか？

P.S. 幸い、TsumiQiita では自動保存されるためデータの変更は無事でした。

【40代 男性 匿名希望】

**Comment by hidao80** [comment]
拝啓
大雨の候、ご住所は大事ないでしょうか。

さて、この度の Issue、完全に盲点でした。寝耳に寝起きバスーカ、と言ったところです。

electron は Chrome Browser がランタイムになっており、ハイパーテキストを踏めば遷移するのは自明なのですが、外部リンクをプレビューして遷移してしまうところまでは考えが至りませんでした。

現在対策を検討中です。取り急ぎ、現状確認をしたところまでご報告いたします。

草々

追伸
location の変更イベントをハンドルして、デフォルトブラウザを起動する方向で調整中です。

**Comment by hidao80** [comment]
@KEINOS リンクをクリックすると、外部リンクの場合はデフォルトブラウザで開くように、内部リンクの場合はノーリアクションになった [Ver.1.7.0](https://github.com/hidao80/TsumiQiita/releases/tag/1.7.0) をリリースしました。お試しください。

**Comment by KEINOS** [comment]
前略

@hidao80 さん、お元気ですか？すっかり蝉の鳴く季節になりましたね。大雨で避難もされたと聞きました。大事なかったでしょうか。

さて、お中元の TsumiQiita 届きました。ありがとう。おかげさまで私の mac でも、リンクを踏んでも大丈夫になりました。とても美味しくいただいています。

気になったのは最初 Chrome さんが「危険物だから届けられない」と配達拒否をしたことです。

@hidao80 さんに限ってそんな怪しいものは送ってこないはずだと、２度ほど再配達をお願いしてもダメだったので、上司を呼べとシークレット・モードで配達を頼んでみたのですが、"darwin" に限っては、やはり危険だからと否定されてしまいました。

<kbd><img width="426" alt="2018-07-14 7 54 03" src="https://user-images.githubusercontent.com/11840938/42717713-ee747942-873d-11e8-9cdb-c05d3fad5991.png"></kbd>
<kbd><img width="414" alt="2018-07-14 7 53 06" src="https://user-images.githubusercontent.com/11840938/42717714-ee9e45b0-873d-11e8-920b-09679117fb37.png"></kbd>

融通が効かないので Firefox さんに業者替えしたところ、すんなり届けてもらい、開梱も滞りなくできました。最近の Chrome さんひどいわね。

もしかすると地元の Chrome さんに問題があるのかもしれませんが、 "darwin" の梱包時にちょっと傷んでいたのかしらと思って、ちょっと気になったのでお知らせしますわね。

まだまだ暑い日々が続きますが、環境が変わると色々と負担がくると言います。くれぐれもお体は大事にね。

あらあらかしこ

**Comment by hidao80** [comment]
@KEINOS 私の環境でも再現しました。
圧縮方法を zip から tar.gz に変更したところ、警告は出なくなりました。
圧縮方法を変更しましたが、相変わらずダブルクリックで解凍できます。
