### ISSUE TITLE
コードブロック内にタグがあると展開されます

### ISSUE THREAD

**Issue by KEINOS** [hidao80/TsumiQiita#44]
インライン・コードは問題ないのですが、コードブロック内にタグがあると展開されてしまいます。

````
`<strong>zero</strong>`

```
<strong>zero</strong>
```

`$ zip -r -X <output file>.zip <input file1> <input file2> ... <input file n>`

```
$ zip -r -X <output file>.zip <input file1> <input file2> ... <input file n>
```
````
👇

<img width="630" alt="2018-07-18 23 05 57" src="https://user-images.githubusercontent.com/11840938/42886724-40340136-8adf-11e8-906f-50d986a83864.png">

特に急ぎとか困っているほどのことではないのですが、`<input file>` で `input` フィールドが出てきたので笑ってしまいました。お手すきで結構ですのでご検討ください。

---

- macOS HighSierra (OSX 10.13.5)
- TsumiQiita v1.7.0

**Comment by hidao80** [comment]
@KEINOS あれあれ〜？ おかしいぞ〜？
…ちょっと調べて見ます。Markdownエンジンレベルではそんな不具合なかったはずなんですけど(^_^;)

**Comment by KEINOS** [comment]
私も code タグに挟まれているなら展開しないと思うのですが、お手数ですがお手すきにお願いいたします。 🙇

**Comment by mafumafuultu** [comment]
functions.js の59、62行目でコードのlang指定が無い場合
タグがエスケープされていないように見えますね。

**Comment by hidao80** [comment]
@mafumafuultu おお！ 有力情報ありがとうございます！ :+1:
まずそこから当たってみます。

**Comment by KEINOS** [comment]
おおっ！すばらしい！ちょっと見づらいですが、確かに `lang` 指定したら表示され 💪 

````
`<strong>zero</strong>`

```html
<strong>zero</strong>
```

`$ zip -r -X <output file>.zip <input file1> <input file2> ... <input file n>`

```shell
$ zip -r -X <output file>.zip <input file1> <input file2> ... <input file n>
```
````
👇
<img width="796" alt="2018-07-19 8 01 50" src="https://user-images.githubusercontent.com/11840938/42912431-4d9dbcb8-8b2a-11e8-8ea7-91f877119efb.png">
